#ifndef __DEMON_SPRITES_H__
#define __DEMON_SPRITES_H__

/*
 * Demon sprite frames
 * Auto-generated by grit_all_frames.py (then trimmed)
 *
 * Total frames: 46  (was 70; right-facing dirs removed, mirrored at render time)
 * Frame size: 56x56 px (7x7 tiles)
 * Tiles per frame: 256 u32 words = 1024 bytes
 *
 * Usage:
 *   copymem((void*)CharMem(n), (void*)DEMON_FRAMES[frameIndex], 1024);
 */

/* Individual frame tile data (each is 256 u32 words = 1024 bytes) */
extern const unsigned int Demon_000Tiles[256];
extern const unsigned int Demon_001Tiles[256];
extern const unsigned int Demon_002Tiles[256];
extern const unsigned int Demon_003Tiles[256];
extern const unsigned int Demon_004Tiles[256];
extern const unsigned int Demon_005Tiles[256];
extern const unsigned int Demon_006Tiles[256];
extern const unsigned int Demon_007Tiles[256];
extern const unsigned int Demon_008Tiles[256];
extern const unsigned int Demon_009Tiles[256];
extern const unsigned int Demon_010Tiles[256];
extern const unsigned int Demon_011Tiles[256];
extern const unsigned int Demon_012Tiles[256];
extern const unsigned int Demon_013Tiles[256];
extern const unsigned int Demon_014Tiles[256];
extern const unsigned int Demon_015Tiles[256];
extern const unsigned int Demon_016Tiles[256];
extern const unsigned int Demon_017Tiles[256];
extern const unsigned int Demon_018Tiles[256];
extern const unsigned int Demon_019Tiles[256];
extern const unsigned int Demon_020Tiles[256];
extern const unsigned int Demon_021Tiles[256];
extern const unsigned int Demon_022Tiles[256];
extern const unsigned int Demon_023Tiles[256];
extern const unsigned int Demon_024Tiles[256];
extern const unsigned int Demon_025Tiles[256];
extern const unsigned int Demon_026Tiles[256];
extern const unsigned int Demon_027Tiles[256];
extern const unsigned int Demon_028Tiles[256];
extern const unsigned int Demon_029Tiles[256];
extern const unsigned int Demon_030Tiles[256];
extern const unsigned int Demon_031Tiles[256];
extern const unsigned int Demon_032Tiles[256];
extern const unsigned int Demon_033Tiles[256];
extern const unsigned int Demon_034Tiles[256];
extern const unsigned int Demon_056Tiles[256];
extern const unsigned int Demon_057Tiles[256];
extern const unsigned int Demon_059Tiles[256];
extern const unsigned int Demon_061Tiles[256];
extern const unsigned int Demon_062Tiles[256];
extern const unsigned int Demon_064Tiles[256];
extern const unsigned int Demon_065Tiles[256];
extern const unsigned int Demon_066Tiles[256];
extern const unsigned int Demon_067Tiles[256];
extern const unsigned int Demon_068Tiles[256];
extern const unsigned int Demon_069Tiles[256];

/* Number of frames */
#define DEMON_FRAME_COUNT 46

/* Bytes per frame (for copymem) */
#define DEMON_FRAME_BYTES 1024

/* Frame pointer table for animation.
 * Old indices 0-34 keep positions 0-34.
 * Old 56->35, 57->36, 59->37, 61->38, 62->39 (pain)
 * Old 64->40 .. 69->45 (death) */
static const unsigned int* const DEMON_FRAMES[46] = {
    Demon_000Tiles,  /*  0 */
    Demon_001Tiles,  /*  1 */
    Demon_002Tiles,  /*  2 */
    Demon_003Tiles,  /*  3 */
    Demon_004Tiles,  /*  4 */
    Demon_005Tiles,  /*  5 */
    Demon_006Tiles,  /*  6 */
    Demon_007Tiles,  /*  7 */
    Demon_008Tiles,  /*  8 */
    Demon_009Tiles,  /*  9 */
    Demon_010Tiles,  /* 10 */
    Demon_011Tiles,  /* 11 */
    Demon_012Tiles,  /* 12 */
    Demon_013Tiles,  /* 13 */
    Demon_014Tiles,  /* 14 */
    Demon_015Tiles,  /* 15 */
    Demon_016Tiles,  /* 16 */
    Demon_017Tiles,  /* 17 */
    Demon_018Tiles,  /* 18 */
    Demon_019Tiles,  /* 19 */
    Demon_020Tiles,  /* 20 */
    Demon_021Tiles,  /* 21 */
    Demon_022Tiles,  /* 22 */
    Demon_023Tiles,  /* 23 */
    Demon_024Tiles,  /* 24 */
    Demon_025Tiles,  /* 25 */
    Demon_026Tiles,  /* 26 */
    Demon_027Tiles,  /* 27 */
    Demon_028Tiles,  /* 28 */
    Demon_029Tiles,  /* 29 */
    Demon_030Tiles,  /* 30 */
    Demon_031Tiles,  /* 31 */
    Demon_032Tiles,  /* 32 */
    Demon_033Tiles,  /* 33 */
    Demon_034Tiles,  /* 34 */
    Demon_056Tiles,  /* 35 = pain dir0 */
    Demon_057Tiles,  /* 36 = pain dir1 */
    Demon_059Tiles,  /* 37 = pain dir2 */
    Demon_061Tiles,  /* 38 = pain dir3 */
    Demon_062Tiles,  /* 39 = pain dir4 */
    Demon_064Tiles,  /* 40 = death 0 */
    Demon_065Tiles,  /* 41 = death 1 */
    Demon_066Tiles,  /* 42 = death 2 */
    Demon_067Tiles,  /* 43 = death 3 */
    Demon_068Tiles,  /* 44 = death 4 */
    Demon_069Tiles   /* 45 = death 5 */
};

#endif /* __DEMON_SPRITES_H__ */
