#ifndef __DEMON_SPRITES_H__
#define __DEMON_SPRITES_H__

/*
 * Demon sprite frames
 * Auto-generated by grit_all_frames.py
 *
 * Total frames: 70
 * Frame size: 56x56 px (7x7 tiles)
 * Tiles per frame: 256 u32 words = 1024 bytes
 *
 * Usage:
 *   // To swap animation frame, copy tile data into char memory:
 *   copymem((void*)CharMem(n), (void*)DEMON_FRAMES[frameIndex], 1024);
 */

/* Individual frame tile data (each is 256 u32 words = 1024 bytes) */
extern const unsigned int Demon_000Tiles[256];
extern const unsigned int Demon_001Tiles[256];
extern const unsigned int Demon_002Tiles[256];
extern const unsigned int Demon_003Tiles[256];
extern const unsigned int Demon_004Tiles[256];
extern const unsigned int Demon_005Tiles[256];
extern const unsigned int Demon_006Tiles[256];
extern const unsigned int Demon_007Tiles[256];
extern const unsigned int Demon_008Tiles[256];
extern const unsigned int Demon_009Tiles[256];
extern const unsigned int Demon_010Tiles[256];
extern const unsigned int Demon_011Tiles[256];
extern const unsigned int Demon_012Tiles[256];
extern const unsigned int Demon_013Tiles[256];
extern const unsigned int Demon_014Tiles[256];
extern const unsigned int Demon_015Tiles[256];
extern const unsigned int Demon_016Tiles[256];
extern const unsigned int Demon_017Tiles[256];
extern const unsigned int Demon_018Tiles[256];
extern const unsigned int Demon_019Tiles[256];
extern const unsigned int Demon_020Tiles[256];
extern const unsigned int Demon_021Tiles[256];
extern const unsigned int Demon_022Tiles[256];
extern const unsigned int Demon_023Tiles[256];
extern const unsigned int Demon_024Tiles[256];
extern const unsigned int Demon_025Tiles[256];
extern const unsigned int Demon_026Tiles[256];
extern const unsigned int Demon_027Tiles[256];
extern const unsigned int Demon_028Tiles[256];
extern const unsigned int Demon_029Tiles[256];
extern const unsigned int Demon_030Tiles[256];
extern const unsigned int Demon_031Tiles[256];
extern const unsigned int Demon_032Tiles[256];
extern const unsigned int Demon_033Tiles[256];
extern const unsigned int Demon_034Tiles[256];
extern const unsigned int Demon_035Tiles[256];
extern const unsigned int Demon_036Tiles[256];
extern const unsigned int Demon_037Tiles[256];
extern const unsigned int Demon_038Tiles[256];
extern const unsigned int Demon_039Tiles[256];
extern const unsigned int Demon_040Tiles[256];
extern const unsigned int Demon_041Tiles[256];
extern const unsigned int Demon_042Tiles[256];
extern const unsigned int Demon_043Tiles[256];
extern const unsigned int Demon_044Tiles[256];
extern const unsigned int Demon_045Tiles[256];
extern const unsigned int Demon_046Tiles[256];
extern const unsigned int Demon_047Tiles[256];
extern const unsigned int Demon_048Tiles[256];
extern const unsigned int Demon_049Tiles[256];
extern const unsigned int Demon_050Tiles[256];
extern const unsigned int Demon_051Tiles[256];
extern const unsigned int Demon_052Tiles[256];
extern const unsigned int Demon_053Tiles[256];
extern const unsigned int Demon_054Tiles[256];
extern const unsigned int Demon_055Tiles[256];
extern const unsigned int Demon_056Tiles[256];
extern const unsigned int Demon_057Tiles[256];
extern const unsigned int Demon_058Tiles[256];
extern const unsigned int Demon_059Tiles[256];
extern const unsigned int Demon_060Tiles[256];
extern const unsigned int Demon_061Tiles[256];
extern const unsigned int Demon_062Tiles[256];
extern const unsigned int Demon_063Tiles[256];
extern const unsigned int Demon_064Tiles[256];
extern const unsigned int Demon_065Tiles[256];
extern const unsigned int Demon_066Tiles[256];
extern const unsigned int Demon_067Tiles[256];
extern const unsigned int Demon_068Tiles[256];
extern const unsigned int Demon_069Tiles[256];

/* Number of frames */
#define DEMON_FRAME_COUNT 70

/* Bytes per frame (for copymem) */
#define DEMON_FRAME_BYTES 1024

/* Frame pointer table for animation */
static const unsigned int* const DEMON_FRAMES[70] = {
    Demon_000Tiles,
    Demon_001Tiles,
    Demon_002Tiles,
    Demon_003Tiles,
    Demon_004Tiles,
    Demon_005Tiles,
    Demon_006Tiles,
    Demon_007Tiles,
    Demon_008Tiles,
    Demon_009Tiles,
    Demon_010Tiles,
    Demon_011Tiles,
    Demon_012Tiles,
    Demon_013Tiles,
    Demon_014Tiles,
    Demon_015Tiles,
    Demon_016Tiles,
    Demon_017Tiles,
    Demon_018Tiles,
    Demon_019Tiles,
    Demon_020Tiles,
    Demon_021Tiles,
    Demon_022Tiles,
    Demon_023Tiles,
    Demon_024Tiles,
    Demon_025Tiles,
    Demon_026Tiles,
    Demon_027Tiles,
    Demon_028Tiles,
    Demon_029Tiles,
    Demon_030Tiles,
    Demon_031Tiles,
    Demon_032Tiles,
    Demon_033Tiles,
    Demon_034Tiles,
    Demon_035Tiles,
    Demon_036Tiles,
    Demon_037Tiles,
    Demon_038Tiles,
    Demon_039Tiles,
    Demon_040Tiles,
    Demon_041Tiles,
    Demon_042Tiles,
    Demon_043Tiles,
    Demon_044Tiles,
    Demon_045Tiles,
    Demon_046Tiles,
    Demon_047Tiles,
    Demon_048Tiles,
    Demon_049Tiles,
    Demon_050Tiles,
    Demon_051Tiles,
    Demon_052Tiles,
    Demon_053Tiles,
    Demon_054Tiles,
    Demon_055Tiles,
    Demon_056Tiles,
    Demon_057Tiles,
    Demon_058Tiles,
    Demon_059Tiles,
    Demon_060Tiles,
    Demon_061Tiles,
    Demon_062Tiles,
    Demon_063Tiles,
    Demon_064Tiles,
    Demon_065Tiles,
    Demon_066Tiles,
    Demon_067Tiles,
    Demon_068Tiles,
    Demon_069Tiles
};

#endif /* __DEMON_SPRITES_H__ */
