#ifndef __WALL_TEXTURES_H__
#define __WALL_TEXTURES_H__

/*
 * Wall texture tiles for VB Doom raycaster.
 * Auto-generated by prepare_wall_textures.py
 * 512 wall + 56 transition = 568 total
 *
 * Layout per texture (128 tiles):
 *   0-63: lit  (8 rows x 8 cols)
 *   64-127: dark (8 rows x 8 cols)
 *
 * Tile index formula:
 *   WALL_TEX_CHAR_START + (wallType-1)*128 + tv*64 + row*8 + (tc >> 5)
 *   tv=0 lit, tv=1 dark; row = (texY >> 13) & 7
 */

#define WALL_TEX_COUNT     4
#define WALL_TEX_COLS      8
#define WALL_TEX_ROWS      8
#define WALL_TEX_PER_TYPE  128
#define WALL_TEX_LIT_BLOCK 64
#define WALL_TEX_TOTAL     512
#define WALL_TEX_BYTES     9088

#define WALL_TEX_CHAR_START  1211

#define TRANS_TEX_CHAR_START  1723
#define TRANS_TEX_COUNT       56

extern const unsigned int wallTextureTiles[2272];

#define WALL_TYPE_STARTAN  1
#define WALL_TYPE_STONE  2
#define WALL_TYPE_TECH  3
#define WALL_TYPE_ROUGH  4

#endif
