#ifndef __ZOMBIE_SGT_SPRITES_H__
#define __ZOMBIE_SGT_SPRITES_H__

/*
 * Zombie Sergeant sprite frames
 * Auto-generated by grit_all_frames.py
 *
 * Total frames: 49
 * Frame size: 56x56 px (7x7 tiles)
 * Tiles per frame: 256 u32 words = 1024 bytes
 *
 * Usage:
 *   // To swap animation frame, copy tile data into char memory:
 *   copymem((void*)CharMem(n), (void*)ZOMBIE_SGT_FRAMES[frameIndex], 1024);
 */

/* Individual frame tile data (each is 256 u32 words = 1024 bytes) */
extern const unsigned int Zombie_Sergeant_000Tiles[256];
extern const unsigned int Zombie_Sergeant_001Tiles[256];
extern const unsigned int Zombie_Sergeant_002Tiles[256];
extern const unsigned int Zombie_Sergeant_003Tiles[256];
extern const unsigned int Zombie_Sergeant_004Tiles[256];
extern const unsigned int Zombie_Sergeant_005Tiles[256];
extern const unsigned int Zombie_Sergeant_006Tiles[256];
extern const unsigned int Zombie_Sergeant_007Tiles[256];
extern const unsigned int Zombie_Sergeant_008Tiles[256];
extern const unsigned int Zombie_Sergeant_009Tiles[256];
extern const unsigned int Zombie_Sergeant_010Tiles[256];
extern const unsigned int Zombie_Sergeant_011Tiles[256];
extern const unsigned int Zombie_Sergeant_012Tiles[256];
extern const unsigned int Zombie_Sergeant_013Tiles[256];
extern const unsigned int Zombie_Sergeant_014Tiles[256];
extern const unsigned int Zombie_Sergeant_015Tiles[256];
extern const unsigned int Zombie_Sergeant_016Tiles[256];
extern const unsigned int Zombie_Sergeant_017Tiles[256];
extern const unsigned int Zombie_Sergeant_018Tiles[256];
extern const unsigned int Zombie_Sergeant_019Tiles[256];
extern const unsigned int Zombie_Sergeant_020Tiles[256];
extern const unsigned int Zombie_Sergeant_021Tiles[256];
extern const unsigned int Zombie_Sergeant_022Tiles[256];
extern const unsigned int Zombie_Sergeant_023Tiles[256];
extern const unsigned int Zombie_Sergeant_024Tiles[256];
extern const unsigned int Zombie_Sergeant_025Tiles[256];
extern const unsigned int Zombie_Sergeant_026Tiles[256];
extern const unsigned int Zombie_Sergeant_027Tiles[256];
extern const unsigned int Zombie_Sergeant_028Tiles[256];
extern const unsigned int Zombie_Sergeant_029Tiles[256];
extern const unsigned int Zombie_Sergeant_030Tiles[256];
extern const unsigned int Zombie_Sergeant_031Tiles[256];
extern const unsigned int Zombie_Sergeant_032Tiles[256];
extern const unsigned int Zombie_Sergeant_033Tiles[256];
extern const unsigned int Zombie_Sergeant_034Tiles[256];
extern const unsigned int Zombie_Sergeant_035Tiles[256];
extern const unsigned int Zombie_Sergeant_036Tiles[256];
extern const unsigned int Zombie_Sergeant_037Tiles[256];
extern const unsigned int Zombie_Sergeant_038Tiles[256];
extern const unsigned int Zombie_Sergeant_039Tiles[256];
extern const unsigned int Zombie_Sergeant_040Tiles[256];
extern const unsigned int Zombie_Sergeant_041Tiles[256];
extern const unsigned int Zombie_Sergeant_042Tiles[256];
extern const unsigned int Zombie_Sergeant_043Tiles[256];
extern const unsigned int Zombie_Sergeant_044Tiles[256];
extern const unsigned int Zombie_Sergeant_045Tiles[256];
extern const unsigned int Zombie_Sergeant_046Tiles[256];
extern const unsigned int Zombie_Sergeant_047Tiles[256];
extern const unsigned int Zombie_Sergeant_048Tiles[256];

/* Number of frames */
#define ZOMBIE_SGT_FRAME_COUNT 49

/* Bytes per frame (for copymem) */
#define ZOMBIE_SGT_FRAME_BYTES 1024

/* Frame pointer table for animation */
static const unsigned int* const ZOMBIE_SGT_FRAMES[49] = {
    Zombie_Sergeant_000Tiles,
    Zombie_Sergeant_001Tiles,
    Zombie_Sergeant_002Tiles,
    Zombie_Sergeant_003Tiles,
    Zombie_Sergeant_004Tiles,
    Zombie_Sergeant_005Tiles,
    Zombie_Sergeant_006Tiles,
    Zombie_Sergeant_007Tiles,
    Zombie_Sergeant_008Tiles,
    Zombie_Sergeant_009Tiles,
    Zombie_Sergeant_010Tiles,
    Zombie_Sergeant_011Tiles,
    Zombie_Sergeant_012Tiles,
    Zombie_Sergeant_013Tiles,
    Zombie_Sergeant_014Tiles,
    Zombie_Sergeant_015Tiles,
    Zombie_Sergeant_016Tiles,
    Zombie_Sergeant_017Tiles,
    Zombie_Sergeant_018Tiles,
    Zombie_Sergeant_019Tiles,
    Zombie_Sergeant_020Tiles,
    Zombie_Sergeant_021Tiles,
    Zombie_Sergeant_022Tiles,
    Zombie_Sergeant_023Tiles,
    Zombie_Sergeant_024Tiles,
    Zombie_Sergeant_025Tiles,
    Zombie_Sergeant_026Tiles,
    Zombie_Sergeant_027Tiles,
    Zombie_Sergeant_028Tiles,
    Zombie_Sergeant_029Tiles,
    Zombie_Sergeant_030Tiles,
    Zombie_Sergeant_031Tiles,
    Zombie_Sergeant_032Tiles,
    Zombie_Sergeant_033Tiles,
    Zombie_Sergeant_034Tiles,
    Zombie_Sergeant_035Tiles,
    Zombie_Sergeant_036Tiles,
    Zombie_Sergeant_037Tiles,
    Zombie_Sergeant_038Tiles,
    Zombie_Sergeant_039Tiles,
    Zombie_Sergeant_040Tiles,
    Zombie_Sergeant_041Tiles,
    Zombie_Sergeant_042Tiles,
    Zombie_Sergeant_043Tiles,
    Zombie_Sergeant_044Tiles,
    Zombie_Sergeant_045Tiles,
    Zombie_Sergeant_046Tiles,
    Zombie_Sergeant_047Tiles,
    Zombie_Sergeant_048Tiles
};

#endif /* __ZOMBIE_SGT_SPRITES_H__ */
