#ifndef __MARINE_SPRITES_H__
#define __MARINE_SPRITES_H__

/*
 * Marine (player 2) sprite frames
 * Auto-generated by prepare_marine_sprites.py
 *
 * Total frames: 51
 * Frame size: 64x64 px (8x8 tiles)
 * Tiles per frame: 256 u32 words = 1024 bytes
 *
 * Frame layout (5 unique directions, mirrored for 8):
 *   0-4:   Walk A, dirs 1-5 (front, front-left, left, back-left, back)
 *   5-9:   Walk B, dirs 1-5
 *   10-14: Walk C, dirs 1-5
 *   15-19: Walk D, dirs 1-5
 *   20-24: Attack E, dirs 1-5
 *   25-29: Attack F, dirs 1-5
 *   30-34: Pain G, dirs 1-5
 *   35-50: Death (direction-independent)
 */

extern const unsigned int marine_000Tiles[256];
extern const unsigned int marine_001Tiles[256];
extern const unsigned int marine_002Tiles[256];
extern const unsigned int marine_003Tiles[256];
extern const unsigned int marine_004Tiles[256];
extern const unsigned int marine_005Tiles[256];
extern const unsigned int marine_006Tiles[256];
extern const unsigned int marine_007Tiles[256];
extern const unsigned int marine_008Tiles[256];
extern const unsigned int marine_009Tiles[256];
extern const unsigned int marine_010Tiles[256];
extern const unsigned int marine_011Tiles[256];
extern const unsigned int marine_012Tiles[256];
extern const unsigned int marine_013Tiles[256];
extern const unsigned int marine_014Tiles[256];
extern const unsigned int marine_015Tiles[256];
extern const unsigned int marine_016Tiles[256];
extern const unsigned int marine_017Tiles[256];
extern const unsigned int marine_018Tiles[256];
extern const unsigned int marine_019Tiles[256];
extern const unsigned int marine_020Tiles[256];
extern const unsigned int marine_021Tiles[256];
extern const unsigned int marine_022Tiles[256];
extern const unsigned int marine_023Tiles[256];
extern const unsigned int marine_024Tiles[256];
extern const unsigned int marine_025Tiles[256];
extern const unsigned int marine_026Tiles[256];
extern const unsigned int marine_027Tiles[256];
extern const unsigned int marine_028Tiles[256];
extern const unsigned int marine_029Tiles[256];
extern const unsigned int marine_030Tiles[256];
extern const unsigned int marine_031Tiles[256];
extern const unsigned int marine_032Tiles[256];
extern const unsigned int marine_033Tiles[256];
extern const unsigned int marine_034Tiles[256];
extern const unsigned int marine_035Tiles[256];
extern const unsigned int marine_036Tiles[256];
extern const unsigned int marine_037Tiles[256];
extern const unsigned int marine_038Tiles[256];
extern const unsigned int marine_039Tiles[256];
extern const unsigned int marine_040Tiles[256];
extern const unsigned int marine_041Tiles[256];
extern const unsigned int marine_042Tiles[256];
extern const unsigned int marine_043Tiles[256];
extern const unsigned int marine_044Tiles[256];
extern const unsigned int marine_045Tiles[256];
extern const unsigned int marine_046Tiles[256];
extern const unsigned int marine_047Tiles[256];
extern const unsigned int marine_048Tiles[256];
extern const unsigned int marine_049Tiles[256];
extern const unsigned int marine_050Tiles[256];

#define MARINE_FRAME_COUNT 51
#define MARINE_FRAME_BYTES 1024
#define MARINE_WALK_ANIM_FRAMES  4
#define MARINE_ATTACK_ANIM_FRAMES 2
#define MARINE_DEATH_FRAMES 16

static const unsigned int* const MARINE_FRAMES[51] = {
    marine_000Tiles,
    marine_001Tiles,
    marine_002Tiles,
    marine_003Tiles,
    marine_004Tiles,
    marine_005Tiles,
    marine_006Tiles,
    marine_007Tiles,
    marine_008Tiles,
    marine_009Tiles,
    marine_010Tiles,
    marine_011Tiles,
    marine_012Tiles,
    marine_013Tiles,
    marine_014Tiles,
    marine_015Tiles,
    marine_016Tiles,
    marine_017Tiles,
    marine_018Tiles,
    marine_019Tiles,
    marine_020Tiles,
    marine_021Tiles,
    marine_022Tiles,
    marine_023Tiles,
    marine_024Tiles,
    marine_025Tiles,
    marine_026Tiles,
    marine_027Tiles,
    marine_028Tiles,
    marine_029Tiles,
    marine_030Tiles,
    marine_031Tiles,
    marine_032Tiles,
    marine_033Tiles,
    marine_034Tiles,
    marine_035Tiles,
    marine_036Tiles,
    marine_037Tiles,
    marine_038Tiles,
    marine_039Tiles,
    marine_040Tiles,
    marine_041Tiles,
    marine_042Tiles,
    marine_043Tiles,
    marine_044Tiles,
    marine_045Tiles,
    marine_046Tiles,
    marine_047Tiles,
    marine_048Tiles,
    marine_049Tiles,
    marine_050Tiles
};

/* Walk frames: [direction][pose] -> frame index */
static const u8 MARINE_WALK_FRAMES[8][4] = {
    { 0,  5, 10, 15},   /* dir 0: front */
    { 1,  6, 11, 16},   /* dir 1: front-left */
    { 2,  7, 12, 17},   /* dir 2: left */
    { 3,  8, 13, 18},   /* dir 3: back-left */
    { 4,  9, 14, 19},   /* dir 4: back */
    { 3,  8, 13, 18},   /* dir 5: back-right (mirror 3) */
    { 2,  7, 12, 17},   /* dir 6: right (mirror 2) */
    { 1,  6, 11, 16},   /* dir 7: front-right (mirror 1) */
};

/* Attack frames: [direction][pose] -> frame index */
static const u8 MARINE_ATTACK_FRAMES[8][2] = {
    {20, 25},   /* dir 0: front */
    {21, 26},   /* dir 1: front-left */
    {22, 27},   /* dir 2: left */
    {23, 28},   /* dir 3: back-left */
    {24, 29},   /* dir 4: back */
    {23, 28},   /* dir 5: back-right (mirror 3) */
    {22, 27},   /* dir 6: right (mirror 2) */
    {21, 26},   /* dir 7: front-right (mirror 1) */
};

/* Pain frames: [direction] -> frame index */
static const u8 MARINE_PAIN_FRAMES[8] = {30, 31, 32, 33, 34, 33, 32, 31};

/* Death frames: sequential starting from 35 */
static const u8 MARINE_DEATH_FRAMES_LUT[16] = {
    35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50
};

#endif /* __MARINE_SPRITES_H__ */
