#ifndef __MARINE_SPRITES_H__
#define __MARINE_SPRITES_H__

/*
 * Marine sprite frames
 * Auto-generated by grit_all_frames.py
 *
 * Total frames: 51
 * Frame size: 56x56 px (7x7 tiles)
 * Tiles per frame: 224 u32 words = 896 bytes
 *
 * Usage:
 *   // To swap animation frame, copy tile data into char memory:
 *   copymem((void*)CharMem(n), (void*)MARINE_FRAMES[frameIndex], 896);
 */

/* Individual frame tile data (each is 224 u32 words = 896 bytes) */
extern const unsigned int Marine_000Tiles[224];
extern const unsigned int Marine_001Tiles[224];
extern const unsigned int Marine_002Tiles[224];
extern const unsigned int Marine_003Tiles[224];
extern const unsigned int Marine_004Tiles[224];
extern const unsigned int Marine_005Tiles[224];
extern const unsigned int Marine_006Tiles[224];
extern const unsigned int Marine_007Tiles[224];
extern const unsigned int Marine_008Tiles[224];
extern const unsigned int Marine_009Tiles[224];
extern const unsigned int Marine_010Tiles[224];
extern const unsigned int Marine_011Tiles[224];
extern const unsigned int Marine_012Tiles[224];
extern const unsigned int Marine_013Tiles[224];
extern const unsigned int Marine_014Tiles[224];
extern const unsigned int Marine_015Tiles[224];
extern const unsigned int Marine_016Tiles[224];
extern const unsigned int Marine_017Tiles[224];
extern const unsigned int Marine_018Tiles[224];
extern const unsigned int Marine_019Tiles[224];
extern const unsigned int Marine_020Tiles[224];
extern const unsigned int Marine_021Tiles[224];
extern const unsigned int Marine_022Tiles[224];
extern const unsigned int Marine_023Tiles[224];
extern const unsigned int Marine_024Tiles[224];
extern const unsigned int Marine_025Tiles[224];
extern const unsigned int Marine_026Tiles[224];
extern const unsigned int Marine_027Tiles[224];
extern const unsigned int Marine_028Tiles[224];
extern const unsigned int Marine_029Tiles[224];
extern const unsigned int Marine_030Tiles[224];
extern const unsigned int Marine_031Tiles[224];
extern const unsigned int Marine_032Tiles[224];
extern const unsigned int Marine_033Tiles[224];
extern const unsigned int Marine_034Tiles[224];
extern const unsigned int Marine_035Tiles[224];
extern const unsigned int Marine_036Tiles[224];
extern const unsigned int Marine_037Tiles[224];
extern const unsigned int Marine_038Tiles[224];
extern const unsigned int Marine_039Tiles[224];
extern const unsigned int Marine_040Tiles[224];
extern const unsigned int Marine_041Tiles[224];
extern const unsigned int Marine_042Tiles[224];
extern const unsigned int Marine_043Tiles[224];
extern const unsigned int Marine_044Tiles[224];
extern const unsigned int Marine_045Tiles[224];
extern const unsigned int Marine_046Tiles[224];
extern const unsigned int Marine_047Tiles[224];
extern const unsigned int Marine_048Tiles[224];
extern const unsigned int Marine_049Tiles[224];
extern const unsigned int Marine_050Tiles[224];

/* Number of frames */
#define MARINE_FRAME_COUNT 51

/* Bytes per frame (for copymem) */
#define MARINE_FRAME_BYTES 896

/* Frame pointer table for animation */
static const unsigned int* const MARINE_FRAMES[51] = {
    Marine_000Tiles,
    Marine_001Tiles,
    Marine_002Tiles,
    Marine_003Tiles,
    Marine_004Tiles,
    Marine_005Tiles,
    Marine_006Tiles,
    Marine_007Tiles,
    Marine_008Tiles,
    Marine_009Tiles,
    Marine_010Tiles,
    Marine_011Tiles,
    Marine_012Tiles,
    Marine_013Tiles,
    Marine_014Tiles,
    Marine_015Tiles,
    Marine_016Tiles,
    Marine_017Tiles,
    Marine_018Tiles,
    Marine_019Tiles,
    Marine_020Tiles,
    Marine_021Tiles,
    Marine_022Tiles,
    Marine_023Tiles,
    Marine_024Tiles,
    Marine_025Tiles,
    Marine_026Tiles,
    Marine_027Tiles,
    Marine_028Tiles,
    Marine_029Tiles,
    Marine_030Tiles,
    Marine_031Tiles,
    Marine_032Tiles,
    Marine_033Tiles,
    Marine_034Tiles,
    Marine_035Tiles,
    Marine_036Tiles,
    Marine_037Tiles,
    Marine_038Tiles,
    Marine_039Tiles,
    Marine_040Tiles,
    Marine_041Tiles,
    Marine_042Tiles,
    Marine_043Tiles,
    Marine_044Tiles,
    Marine_045Tiles,
    Marine_046Tiles,
    Marine_047Tiles,
    Marine_048Tiles,
    Marine_049Tiles,
    Marine_050Tiles
};

#endif /* __MARINE_SPRITES_H__ */
