#ifndef __ZOMBIE_SPRITES_H__
#define __ZOMBIE_SPRITES_H__

/*
 * Zombie sprite frames
 * Auto-generated by grit_all_frames.py
 *
 * Total frames: 49
 * Frame size: 56x56 px (7x7 tiles)
 * Tiles per frame: 256 u32 words = 1024 bytes
 *
 * Usage:
 *   // To swap animation frame, copy tile data into char memory:
 *   copymem((void*)CharMem(n), (void*)ZOMBIE_FRAMES[frameIndex], 1024);
 */

/* Individual frame tile data (each is 256 u32 words = 1024 bytes) */
extern const unsigned int Zombie_000Tiles[256];
extern const unsigned int Zombie_001Tiles[256];
extern const unsigned int Zombie_002Tiles[256];
extern const unsigned int Zombie_003Tiles[256];
extern const unsigned int Zombie_004Tiles[256];
extern const unsigned int Zombie_005Tiles[256];
extern const unsigned int Zombie_006Tiles[256];
extern const unsigned int Zombie_007Tiles[256];
extern const unsigned int Zombie_008Tiles[256];
extern const unsigned int Zombie_009Tiles[256];
extern const unsigned int Zombie_010Tiles[256];
extern const unsigned int Zombie_011Tiles[256];
extern const unsigned int Zombie_012Tiles[256];
extern const unsigned int Zombie_013Tiles[256];
extern const unsigned int Zombie_014Tiles[256];
extern const unsigned int Zombie_015Tiles[256];
extern const unsigned int Zombie_016Tiles[256];
extern const unsigned int Zombie_017Tiles[256];
extern const unsigned int Zombie_018Tiles[256];
extern const unsigned int Zombie_019Tiles[256];
extern const unsigned int Zombie_020Tiles[256];
extern const unsigned int Zombie_021Tiles[256];
extern const unsigned int Zombie_022Tiles[256];
extern const unsigned int Zombie_023Tiles[256];
extern const unsigned int Zombie_024Tiles[256];
extern const unsigned int Zombie_025Tiles[256];
extern const unsigned int Zombie_026Tiles[256];
extern const unsigned int Zombie_027Tiles[256];
extern const unsigned int Zombie_028Tiles[256];
extern const unsigned int Zombie_029Tiles[256];
extern const unsigned int Zombie_030Tiles[256];
extern const unsigned int Zombie_031Tiles[256];
extern const unsigned int Zombie_032Tiles[256];
extern const unsigned int Zombie_033Tiles[256];
extern const unsigned int Zombie_034Tiles[256];
extern const unsigned int Zombie_035Tiles[256];
extern const unsigned int Zombie_036Tiles[256];
extern const unsigned int Zombie_037Tiles[256];
extern const unsigned int Zombie_038Tiles[256];
extern const unsigned int Zombie_039Tiles[256];
extern const unsigned int Zombie_040Tiles[256];
extern const unsigned int Zombie_041Tiles[256];
extern const unsigned int Zombie_042Tiles[256];
extern const unsigned int Zombie_043Tiles[256];
extern const unsigned int Zombie_044Tiles[256];
extern const unsigned int Zombie_045Tiles[256];
extern const unsigned int Zombie_046Tiles[256];
extern const unsigned int Zombie_047Tiles[256];
extern const unsigned int Zombie_048Tiles[256];

/* Number of frames */
#ifndef ZOMBIE_FRAME_COUNT
#define ZOMBIE_FRAME_COUNT 49
#endif

/* Bytes per frame (for copymem) */
#ifndef ZOMBIE_FRAME_BYTES
#define ZOMBIE_FRAME_BYTES 1024
#endif

/* Frame pointer table for animation */
static const unsigned int* const ZOMBIE_FRAMES[49] = {
    Zombie_000Tiles,
    Zombie_001Tiles,
    Zombie_002Tiles,
    Zombie_003Tiles,
    Zombie_004Tiles,
    Zombie_005Tiles,
    Zombie_006Tiles,
    Zombie_007Tiles,
    Zombie_008Tiles,
    Zombie_009Tiles,
    Zombie_010Tiles,
    Zombie_011Tiles,
    Zombie_012Tiles,
    Zombie_013Tiles,
    Zombie_014Tiles,
    Zombie_015Tiles,
    Zombie_016Tiles,
    Zombie_017Tiles,
    Zombie_018Tiles,
    Zombie_019Tiles,
    Zombie_020Tiles,
    Zombie_021Tiles,
    Zombie_022Tiles,
    Zombie_023Tiles,
    Zombie_024Tiles,
    Zombie_025Tiles,
    Zombie_026Tiles,
    Zombie_027Tiles,
    Zombie_028Tiles,
    Zombie_029Tiles,
    Zombie_030Tiles,
    Zombie_031Tiles,
    Zombie_032Tiles,
    Zombie_033Tiles,
    Zombie_034Tiles,
    Zombie_035Tiles,
    Zombie_036Tiles,
    Zombie_037Tiles,
    Zombie_038Tiles,
    Zombie_039Tiles,
    Zombie_040Tiles,
    Zombie_041Tiles,
    Zombie_042Tiles,
    Zombie_043Tiles,
    Zombie_044Tiles,
    Zombie_045Tiles,
    Zombie_046Tiles,
    Zombie_047Tiles,
    Zombie_048Tiles
};

#endif /* __ZOMBIE_SPRITES_H__ */
