#ifndef __PICKUP_SPRITES_H__
#define __PICKUP_SPRITES_H__

/*
 * Pickup sprite tile data
 * Auto-generated by crop_pickups.py
 * Tile grid: 32x24 px (4x3 tiles)
 * Tiles per frame: 12
 * Bytes per frame: 192
 */

/* Tile size constants defined in pickup.h */

extern const unsigned int pickup_ammo_clipTiles[48];
extern const unsigned int pickup_health_largeTiles[48];
extern const unsigned int pickup_health_smallTiles[48];

/* Indexed by pickup type: 0=ammo_clip, 1=health_small, 2=health_large */
static const unsigned int* const PICKUP_TILES[3] = {
    pickup_ammo_clipTiles,
    pickup_health_smallTiles,
    pickup_health_largeTiles
};

#endif /* __PICKUP_SPRITES_H__ */
