#ifndef __TELEPORT_SPRITES_H__
#define __TELEPORT_SPRITES_H__

/*
 * Teleport fog animation sprite frames
 * Auto-generated by prepare_teleport_sprites.py
 *
 * Total frames: 10
 * Frame size: 64x64 px (8x8 tiles)
 * Tiles per frame: 256 u32 words = 1024 bytes
 *
 * Frame layout: TFOGA0 through TFOGJ0 (10 sequential frames)
 */

extern const unsigned int teleport_00Tiles[256];
extern const unsigned int teleport_01Tiles[256];
extern const unsigned int teleport_02Tiles[256];
extern const unsigned int teleport_03Tiles[256];
extern const unsigned int teleport_04Tiles[256];
extern const unsigned int teleport_05Tiles[256];
extern const unsigned int teleport_06Tiles[256];
extern const unsigned int teleport_07Tiles[256];
extern const unsigned int teleport_08Tiles[256];
extern const unsigned int teleport_09Tiles[256];

#define TELEPORT_SPRITE_FRAME_COUNT 10
#define TELEPORT_SPRITE_FRAME_BYTES 1024

static const unsigned int* const TELEPORT_FRAMES[10] = {
    teleport_00Tiles,
    teleport_01Tiles,
    teleport_02Tiles,
    teleport_03Tiles,
    teleport_04Tiles,
    teleport_05Tiles,
    teleport_06Tiles,
    teleport_07Tiles,
    teleport_08Tiles,
    teleport_09Tiles
};

#endif /* __TELEPORT_SPRITES_H__ */
