#ifndef __IMP_SPRITES_H__
#define __IMP_SPRITES_H__

/*
 * Imp sprite frames
 * Auto-generated by grit_all_frames.py
 *
 * Total frames: 56
 * Frame size: 56x56 px (7x7 tiles)
 * Tiles per frame: 256 u32 words = 1024 bytes
 *
 * Usage:
 *   // To swap animation frame, copy tile data into char memory:
 *   copymem((void*)CharMem(n), (void*)IMP_FRAMES[frameIndex], 1024);
 */

/* Individual frame tile data (each is 256 u32 words = 1024 bytes) */
extern const unsigned int Imp_000Tiles[256];
extern const unsigned int Imp_001Tiles[256];
extern const unsigned int Imp_002Tiles[256];
extern const unsigned int Imp_003Tiles[256];
extern const unsigned int Imp_004Tiles[256];
extern const unsigned int Imp_005Tiles[256];
extern const unsigned int Imp_006Tiles[256];
extern const unsigned int Imp_007Tiles[256];
extern const unsigned int Imp_008Tiles[256];
extern const unsigned int Imp_009Tiles[256];
extern const unsigned int Imp_010Tiles[256];
extern const unsigned int Imp_011Tiles[256];
extern const unsigned int Imp_012Tiles[256];
extern const unsigned int Imp_013Tiles[256];
extern const unsigned int Imp_014Tiles[256];
extern const unsigned int Imp_015Tiles[256];
extern const unsigned int Imp_016Tiles[256];
extern const unsigned int Imp_017Tiles[256];
extern const unsigned int Imp_018Tiles[256];
extern const unsigned int Imp_019Tiles[256];
extern const unsigned int Imp_020Tiles[256];
extern const unsigned int Imp_021Tiles[256];
extern const unsigned int Imp_022Tiles[256];
extern const unsigned int Imp_023Tiles[256];
extern const unsigned int Imp_024Tiles[256];
extern const unsigned int Imp_025Tiles[256];
extern const unsigned int Imp_026Tiles[256];
extern const unsigned int Imp_027Tiles[256];
extern const unsigned int Imp_028Tiles[256];
extern const unsigned int Imp_029Tiles[256];
extern const unsigned int Imp_030Tiles[256];
extern const unsigned int Imp_031Tiles[256];
extern const unsigned int Imp_032Tiles[256];
extern const unsigned int Imp_033Tiles[256];
extern const unsigned int Imp_034Tiles[256];
extern const unsigned int Imp_035Tiles[256];
extern const unsigned int Imp_036Tiles[256];
extern const unsigned int Imp_037Tiles[256];
extern const unsigned int Imp_038Tiles[256];
extern const unsigned int Imp_039Tiles[256];
extern const unsigned int Imp_040Tiles[256];
extern const unsigned int Imp_041Tiles[256];
extern const unsigned int Imp_042Tiles[256];
extern const unsigned int Imp_043Tiles[256];
extern const unsigned int Imp_044Tiles[256];
extern const unsigned int Imp_045Tiles[256];
extern const unsigned int Imp_046Tiles[256];
extern const unsigned int Imp_047Tiles[256];
extern const unsigned int Imp_048Tiles[256];
extern const unsigned int Imp_049Tiles[256];
extern const unsigned int Imp_050Tiles[256];
extern const unsigned int Imp_051Tiles[256];
extern const unsigned int Imp_052Tiles[256];
extern const unsigned int Imp_053Tiles[256];
extern const unsigned int Imp_054Tiles[256];
extern const unsigned int Imp_055Tiles[256];

/* Number of frames */
#define IMP_FRAME_COUNT 56

/* Bytes per frame (for copymem) */
#define IMP_FRAME_BYTES 1024

/* Frame pointer table for animation */
static const unsigned int* const IMP_FRAMES[56] = {
    Imp_000Tiles,
    Imp_001Tiles,
    Imp_002Tiles,
    Imp_003Tiles,
    Imp_004Tiles,
    Imp_005Tiles,
    Imp_006Tiles,
    Imp_007Tiles,
    Imp_008Tiles,
    Imp_009Tiles,
    Imp_010Tiles,
    Imp_011Tiles,
    Imp_012Tiles,
    Imp_013Tiles,
    Imp_014Tiles,
    Imp_015Tiles,
    Imp_016Tiles,
    Imp_017Tiles,
    Imp_018Tiles,
    Imp_019Tiles,
    Imp_020Tiles,
    Imp_021Tiles,
    Imp_022Tiles,
    Imp_023Tiles,
    Imp_024Tiles,
    Imp_025Tiles,
    Imp_026Tiles,
    Imp_027Tiles,
    Imp_028Tiles,
    Imp_029Tiles,
    Imp_030Tiles,
    Imp_031Tiles,
    Imp_032Tiles,
    Imp_033Tiles,
    Imp_034Tiles,
    Imp_035Tiles,
    Imp_036Tiles,
    Imp_037Tiles,
    Imp_038Tiles,
    Imp_039Tiles,
    Imp_040Tiles,
    Imp_041Tiles,
    Imp_042Tiles,
    Imp_043Tiles,
    Imp_044Tiles,
    Imp_045Tiles,
    Imp_046Tiles,
    Imp_047Tiles,
    Imp_048Tiles,
    Imp_049Tiles,
    Imp_050Tiles,
    Imp_051Tiles,
    Imp_052Tiles,
    Imp_053Tiles,
    Imp_054Tiles,
    Imp_055Tiles
};

#endif /* __IMP_SPRITES_H__ */
